const reviewText = [
    `Wonderful experience. Our family of five would definitely return. My 3 boys (all under 6) loved checking out the farm animals, playing in the creek, exploring the woods, and enjoying the swings. We stayed at site 1 and can’t wait to come back. Make sure you preorder some cinnamon rolls for the morning deform Sheila! Bonus, Wooly Pig Farm Brewery is less than 10 minutes away. A couple Crowlers over the campfire was perfect.`,
    `We loved this site. It was secluded and beautiful. The water spigot and port-a-potty were close by and very clean. I would definitely stay here again.`,
    `I love this place! It is absolutely beautiful! I would definitely camp here again!!`,
    `Very private and beautiful spot. There is a road on the other side of the creek that was a bit loud at times but otherwise everything was perfect!`,
    `My friend and I came for a weekend night and had such a magical time :) the views looking down into the meadow where the horses graze were truly enchanting... our host was very friendly and offered more amenities than were originally offered when we purchased on Hipcamp! We paid $20 for two firewood bundles and cozied up for the night under the most gorgeous starry night sky. Truly speculate! In the early morning light we walked about half the perimeter of the meadow and two of the horses came up to us for a nice pet, very sweet. I would return here again and again, it was a perfect camping experience!`,
    `It was so magical! We came for fourth of July weekend because we wanted to escape the fireworks in LA. The grounds are beautiful and dog friendly. It's a former Boy Scout camp, so there's lots of interesting buildings and parts leftover from that. There's also the horses! We stayed by the meadow and had a view of the horses each night. Our last night there we walked down to the fence for sunset and the horses eventually all came up to say hi! It was absolutely amazing and breathtaking! I really loved camping here. The drive into the grounds was a bit rough for my Prius, so take it slow and don't get here late/after dark for less stress. Overall, I would definitely recommend this place.`,
    `This place was amazing, the site was very private and beautiful, enough room for our dog to run around and the kids to play freely. We can't wait to come back!`,
    `Our stay at the farm was so so great! Lots of space for multiple tents and great big bonfire spot. The trail to get to the site is a little bit rough for low riding cars but we made it in our minivan just fine! Definitely a really secluded spot that would be perfect for a big group of people with 4x4s, although not necessary it to get there. We also happened to stay just when the pigs had piglets and they were so unbelievably cute and tiny! Ask about fresh eggs and lettuce too! You're staying on a working farm so there's a ton of yummy homegrown options!`,
    `I wanted to take my 4 year old camping, and i wanted someplace private. Because it was just me and my son I was concerned about feeling safe, but I would go back again - I felt very safe. Frank was a great host, and very knowledgable. I would definitely recommend this site.`,
    `We loved our site and wished we could have stayed longer. We camped a bit deeper out into the property, at the site with the lean-to, right next to the creek. We were able to drive most of the way out there, and the jaunt up/down the hill with plenty of equipment was no big deal. Host was very friendly and brought our firewood all the way out to the site in his tractor. We ended up buying some bacon, sausage, and eggs from him too. Had it for breakfast and dinner the day afterward -- would definitely recommend.`,
    `Very simple exactly what we expected! Very clean and private`,
    `Site was really lovely- accessible (though slowly) with our 2WD sedan, very secluded (we didn’t see or hear any of the other campers). Host was very friendly and helpful and had enough firewood for us for our two night stay, and the creek was as lovely and refreshing (though not really deep enough for swimming). Only downside was that you could hear what we assumed was a shooting range.`,
    `Staying here was a blast, we enjoyed the large, private campsite and spent much of the day walking around the creek and seeing signs of beavers. Around noon on Saturday, Frank came by with a truck and set up a picnic at our site, so it’s clear that he’s going the extra mile to make the sites here nice and inviting. I look forward to returning and trying another site next time, I recommend visiting to anyone on the fence!`,
    `Very private and well kept campground with firewood provided!`,
    `We have been wanting to venture from traditional camping to more off-grid camping and this was a great segue for us. The kids loved petting the piglets, the site was very private, the creek was so beautifully clean. Such a beautiful property to stay on and our site (Beaver creek) felt just the right amount of remote. The bacon, sausage and eggs from the farm were delicious. We didn't venture out too much because the weather was a bit dreary but we would love to come back and explore the area more next time.`,
    `We ended up just staying in the cabin but highly recommend it and I’m sure the tent sites are equally nice.. It was very clean and had a nice fire pit. We bought some farm fresh eggs, sausages and chicken. We got local brewery and hiking recommendations from Frank as well. We highly recommend staying here and hope to be back soon!`,
    `The Crooked Creek Hollow Farm is a real gem in New Hampshire! The campsites are very private and the one that my girlfriend and I stayed at even had a brook next to it. The forest is full of different types of berries that you can enjoy while discovering the surroundings. You can even purchase sausages and fresh farm eggs from the family. The whole campsite is super neat, well organized and extremely clean. We will definitely stay there next time we visit New Hampshire. Thank you for making our stay so lovely.`,
    `The entire place was super nice. Although the road in was a little bumpy, as long as you have a larger car, it should be fine. The campsite was very tranquil and super nice; there were sounds of wildlife every night and the trees were cleared enough that you could stargaze on starry nights. The sausage and beef provided were amazing and the hosts wife (with whom I met on arrival) was very friendly and helpful.`,
    `What a perfect weekend! The campsite was clean, private and picturesque with good flat space for pitching two tents. The farm is beautiful. Host was helpful and easy to reach. Thanks so much!`,
  ]

module.exports = reviewText;
